sudo: required
dist: trusty
language: generic
services:
- docker
env:
  global:
  - KCPTUN_VER=20160912
  - SS_VER=latest
  matrix:
  - URL=https://www.facebook.com/
  - URL=https://www.google.com/
  - URL=https://www.twitter.com/
  - URL=https://www.youtube.com/
before_install:
- docker build -t vmlinz/kcptun:$KCPTUN_VER .
- docker run -d -p 127.0.0.1:8388:8388 -e PASSWORD=helloss --name ss-server easypi/shadowsocks-libev:$SS_VER
- docker run -d -p 127.0.0.1:38388:38388/udp -e KEY=hellokcp -e TARGET_ADDR=ss-server
  -e TARGET_PORT=8388 -e LISTEN_ADDR=0.0.0.0 -e LISTEN_PORT=38388 --link ss-server:ss-server
  --name kcptun-server vmlinz/kcptun:$KCPTUN_VER
- docker run -d -p 127.0.0.1:38387:38387 --link kcptun-server:kcptun-server --name
  kcptun-client vmlinz/kcptun:$KCPTUN_VER client_linux_amd64 -l 0.0.0.0:38387 -r kcptun-server:38388
  --key hellokcp --mode fast2 --conn 4
- docker run -d -p 127.0.0.1:1080:1080 --link kcptun-client:kcptun-client --name ss-client
  easypi/shadowsocks-libev:$SS_VER ss-local -s kcptun-client -p 38387 -m aes-256-cfb
  -k helloss -b 0.0.0.0 -l 31080 -t 300 --fast-open
- docker run -d -p 127.0.0.1:1080:1080 --link kcptun-client:kcptun-client --name ss-client
  easypi/shadowsocks-libev:$SS_VER ss-local -s 127.0.0.1 -p 8388 -m aes-256-cfb -k
  helloss -b 0.0.0.0 -l 1080 -t 300 --fast-open
- docker ps -a
script:
- curl -I -x socks5h://127.0.0.1:1080 $URL
- curl -I -x socks5h://127.0.0.1:31080 $URL
after_success: if [[ $TRAVIS_TAG && $URL == *youtube* ]]; then docker login -e="$DOCKER_EMAIL"
  -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker tag vmlinz/kcptun:$KCPTUN_VER
  vmlinz/kcptun:latest; docker push vmlinz/kcptun:$KCPTUN_VER; docker push vmlinz/kcptun:latest;
  fi
notifications:
  slack:
    secure: nnCvwBXDts8ojsErxdWYZFy0eg+lH7jVXMsBDlyeXj3KH5UCjYTKRo3eHeLihQq9i+FhEoBfcBzkCWqc4WXaNVrHl88yCdePrsI6G7BcPKK2tVH8akhGouuD2TFaN1Ne9NQuc38s5cj6IDKK9RvbuntaBxcFeYy7w8bVw/IMVyi4M8iSdASFnzbFQkcbBcQsW4xtE/9PZRG3ey6F2SzAv4czGM/2rxqPTqbBGbRvxyWbNNxn7pw0bR4OZycc3E3icXGTLTYtUiW4/LVUF/vJfkMzPo+tq4N8NBp/2u2X+G8xKLd2y5KNW4Q6+jXwscisyRSt5vXQXa6GCJ+FSAQRhXCtxkmApE8CPW4/iHHT9ypEkj6cb0ewZIFN+vpvf1tJQxeMiGguO26qjhAPhx73Z2rxTUfGU7Oihm5fo/kWIVFZT4I6MNPJJYRPNG6EZ3s4nNflFJeiRJl5V/SHL+rCxB5uSykcetQQmRdmUtTkq0zBdWGXeYCibDI3lu/kCAmX3w8X536Bs4eZUl0rtLYN/liXAzqLzAjw37zCKbAvrMQevxO7zeqhaxh1xVLw7lTVaA3j9uJQlvmpoobd0TdVTrzmAVgDTeKY3emG3UHELkO6lIu+X0qqBp6hrFfLNcC0WClMPMaAGhYxPIiO1g89v7dZXV6O8Vw/Bi/zlKcEOCE=
